name: Trigger telnyx_b2bua_builder
on:
  push:
    branches:
      - master
      - main
      - deploy-*
      - release-*
  pull_request:
    branches:
      - master
      - main
      - deploy-*
      - release-*

jobs:
  trigger:
    runs-on: telnyx-small
    steps:
      - name: Trigger upstream build
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            const branchName = context.eventName === 'pull_request'
              ? context.payload.pull_request.head.ref
              : context.ref.replace('refs/heads/', '');
            console.log(`Triggering telnyx_b2bua_builder workflow for branch: ${branchName}`);

            await github.rest.repos.createDispatchEvent({
              owner: 'team-telnyx',
              repo: 'telnyx_b2bua_builder',
              event_type: 'upstream-build',
              client_payload: {
                branch: branchName
              }
            });
            console.log('Successfully triggered repository_dispatch');
